### ISSUE TITLE
Failed to connect to onedrive for business

### ISSUE THREAD

**Issue by quen2404** [derrix060/onedriveClient#30] opened 2018-10-22 10:48 UTC
Hello,
i'm trying to use your client to connect to my onedrive for business account. But i have an error:

```
onedrived-pref account add -b
NOTE: To better manage your OneDrive accounts, onedrived needs permission to access your account info (e.g., email address to distinguish different accounts) and read/write your OneDrive files.

Paste this URL into your browser to sign in and authorize onedrived:

https://login.microsoftonline.com/common/oauth2/authorize?client_id=6fdb55b4-c905-4612-bd23-306c3918217c&response_type=code&redirect_uri=https%3A%2F%2Fod.cnbeining.com&scope=U+s+e+r+.+R+e+a+d+++o+f+f+l+i+n+e+_+a+c+c+e+s+s

The authentication web page will finish with a blank page whose URL starts with "https://od.cnbeining.com". Paste this URL after the prompt.
Paste URL here: https://od.cnbeining.com/?XXXX
Need authenticate again to get personal information'
Paste this URL into your browser to sign in and authorize onedrived:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=0e170d2c-0ac5-4a4f-9099-c6bb0fb52d0c&response_type=code&redirect_uri=https://onedrivesite.mario-apra.tk/&scope=User.Read offline_access

The authentication web page will finish with a blank page whose URL starts with "https://onedrivesite.mario-apra.tk/". Paste this URL after the prompt.
Paste URL here: https://onedrivesite.mario-apra.tk/?XXXX

Failed to authorize onedrived: list index out of range.
```

Does someone has already experienced that kind of issue ?

**Comment by Modelmat** [comment] 2018-10-22 12:18
Closing this as duplicate of #29.

**Closed by Modelmat** 2018-10-22 12:18 UTC

**Comment by quen2404** [comment] 2018-10-22 12:38
Sorry for the duplicate ! :thinking: I don't understand why it was created twice.
